[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
backgroundColor = "#080c14"
secondaryBackgroundColor = "#0d1b2a"
textColor = "#ccd6f6"
font = "sans serif"

[browser]
gatherUsageStats = false
